name: Publish HEAD
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to be published"
        required: true
        default: "main"
jobs:
  call-kmmbridge-publish:
    name: "Publish iOS HEAD Version Artifact"
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.8
    secrets:
      gradle_params: -Pversiontype=Snapshot
