name: Publish HEAD
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to be published"
        required: true
        default: "main"
jobs:
  dev:
    name: "Publish HEAD Version Artifact"
    runs-on: self-hosted
    permissions:
      repository-projects: write
      contents: write
      packages: write
      checks: write
    steps:
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew
      - name: Get HEAD name
        run: |
          export HASH_NAME=`git rev-parse --short HEAD`
          echo "hash_name=$HASH_NAME" >> $GITHUB_ENV
      - name: Set environment variable
        run: echo "export VERSION_TYPE=SNAPSHOT-$HASH_NAME" >> $GITHUB_ENV
  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.8
    needs: dev
